fail_fast: true
repos:
- repo: local
  hooks:
  - id: run isort
    name: isort
    language: python
    entry: python -m isort --check-only
    types: [python]
    additional_dependencies: ['isort']
    language_version: python3.10

  - id: black
    name: black
    entry: black --check
    language: python
    types: [python]
    additional_dependencies: ['black']
    language_version: python3.10

  - id: bandit
    name: bandit
    entry: python3 -m bandit -r app
    language: python
    types: [python]
    additional_dependencies: ['bandit']
    language_version: python3.10

  - id: run unittests
    name: pytest
    entry: python -m pytest --cov=app/
    language: python
    additional_dependencies: ['pytest']
    language_version: python3.10
