version: "2.2"

services:
  mongo:
    container_name: mongo
    image: mongo:3.6
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
